backend_usuario:
    path:     /
    defaults: { _controller: "BackendBundle:Usuario:index" }

backend_usuario_show:
    path:     /{id}/show
    defaults: { _controller: "BackendBundle:Usuario:show" }

backend_usuario_new:
    path:     /new
    defaults: { _controller: "BackendBundle:Usuario:new" }

backend_usuario_create:
    path:     /create
    defaults: { _controller: "BackendBundle:Usuario:create" }
    requirements: { _method: post }

backend_usuario_edit:
    path:     /{id}/edit
    defaults: { _controller: "BackendBundle:Usuario:edit" }

backend_usuario_update:
    path:     /{id}/update
    defaults: { _controller: "BackendBundle:Usuario:update" }
    requirements: { _method: post|put }

backend_usuario_delete:
    path:     /{id}/delete
    defaults: { _controller: "BackendBundle:Usuario:delete" }
    requirements: { _method: post|delete }
