usuario:
    resource: "@UsuarioBundle/Resources/config/routing.yml"
    prefix:   /

tienda:
    resource: "@TiendaBundle/Resources/config/routing.yml"
    prefix:   /

ciudad:
    resource: "@CiudadBundle/Resources/config/routing.yml"
    prefix:   /

oferta:
    resource: "@OfertaBundle/Resources/config/routing.yml"
    prefix:   /

pagina_estatica:
    path:     /sitio/{pagina}/
    defaults: { _controller: OfertaBundle:Sitio:estatica }

portada:
    path:     /{ciudad}
    defaults: { _controller: OfertaBundle:Default:portada }

_portada:
    path:     /
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: portada, ciudad:'%cupon.ciudad_por_defecto%' }

ciudad_cambiar:
    path:     /ciudad/cambiar-a-{ciudad}
    defaults: { _controller: CiudadBundle:Default:cambiar }
    requirements:
        ciudad: .+
oferta:
    path:     /{ciudad}/ofertas/{slug}
    defaults: { _controller: OfertaBundle:Default:oferta }

UsuarioBundle:
    resource: "@UsuarioBundle/Resources/config/routing.yml"
    prefix: /usuario

Extranet:
    resource: '@TiendaBundle/Resources/config/extranet/routing.yml'
    prefix: /extranet