security:
    firewalls:
        extranet:
          pattern: ^/extranet
          provider: tiendas
          anonymous: ~
          form_login:
              login_path: /extranet/login
              check_path: /extranet/login_check
          logout:
              path: extranet_logout
        
        frontend:
          pattern: ^/*
          provider: usuarios
          anonymous: ~
          form_login:
              login_path: usuario_login
              check_path: usuario_login_check
              use_referer: true
          logout:
              path: usuario_logout
          remember_me:
              key: cupon1234
              lifetime: 3600

    access_control:
        - { path: ^/usuario/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/usuario/registro, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/usuario/*, roles: ROLE_USUARIO }
        - { path: ^/extranet/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/extranet/*, roles: ROLE_TIENDA }

    providers:
        usuarios:
              entity: { class: Cupon\UsuarioBundle\Entity\Usuario, property: email }
        tiendas:
              entity: { class: Cupon\TiendaBundle\Entity\Tienda, property: login }

    #cambiar plaintext a la otra encriptación
    encoders:
        Cupon\UsuarioBundle\Entity\Usuario: plaintext
        Cupon\TiendaBundle\Entity\Usuario: plaintext

    access_decision_manager:
        strategy: unanimous