<?php

namespace Proxies\__CG__\Cupon\OfertaBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Oferta extends \Cupon\OfertaBundle\Entity\Oferta implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Cupon\\OfertaBundle\\Entity\\Oferta' . "\0" . 'id', '' . "\0" . 'Cupon\\OfertaBundle\\Entity\\Oferta' . "\0" . 'nombre', '' . "\0" . 'Cupon\\OfertaBundle\\Entity\\Oferta' . "\0" . 'slug', '' . "\0" . 'Cupon\\OfertaBundle\\Entity\\Oferta' . "\0" . 'descripcion', '' . "\0" . 'Cupon\\OfertaBundle\\Entity\\Oferta' . "\0" . 'condiciones', '' . "\0" . 'Cupon\\OfertaBundle\\Entity\\Oferta' . "\0" . 'rutaFoto', '' . "\0" . 'Cupon\\OfertaBundle\\Entity\\Oferta' . "\0" . 'precio', '' . "\0" . 'Cupon\\OfertaBundle\\Entity\\Oferta' . "\0" . 'descuento', '' . "\0" . 'Cupon\\OfertaBundle\\Entity\\Oferta' . "\0" . 'fechaPublicacion', '' . "\0" . 'Cupon\\OfertaBundle\\Entity\\Oferta' . "\0" . 'fechaExpiracion', '' . "\0" . 'Cupon\\OfertaBundle\\Entity\\Oferta' . "\0" . 'compras', '' . "\0" . 'Cupon\\OfertaBundle\\Entity\\Oferta' . "\0" . 'umbral', '' . "\0" . 'Cupon\\OfertaBundle\\Entity\\Oferta' . "\0" . 'revisada', '' . "\0" . 'Cupon\\OfertaBundle\\Entity\\Oferta' . "\0" . 'ciudad', '' . "\0" . 'Cupon\\OfertaBundle\\Entity\\Oferta' . "\0" . 'tienda');
        }

        return array('__isInitialized__', '' . "\0" . 'Cupon\\OfertaBundle\\Entity\\Oferta' . "\0" . 'id', '' . "\0" . 'Cupon\\OfertaBundle\\Entity\\Oferta' . "\0" . 'nombre', '' . "\0" . 'Cupon\\OfertaBundle\\Entity\\Oferta' . "\0" . 'slug', '' . "\0" . 'Cupon\\OfertaBundle\\Entity\\Oferta' . "\0" . 'descripcion', '' . "\0" . 'Cupon\\OfertaBundle\\Entity\\Oferta' . "\0" . 'condiciones', '' . "\0" . 'Cupon\\OfertaBundle\\Entity\\Oferta' . "\0" . 'rutaFoto', '' . "\0" . 'Cupon\\OfertaBundle\\Entity\\Oferta' . "\0" . 'precio', '' . "\0" . 'Cupon\\OfertaBundle\\Entity\\Oferta' . "\0" . 'descuento', '' . "\0" . 'Cupon\\OfertaBundle\\Entity\\Oferta' . "\0" . 'fechaPublicacion', '' . "\0" . 'Cupon\\OfertaBundle\\Entity\\Oferta' . "\0" . 'fechaExpiracion', '' . "\0" . 'Cupon\\OfertaBundle\\Entity\\Oferta' . "\0" . 'compras', '' . "\0" . 'Cupon\\OfertaBundle\\Entity\\Oferta' . "\0" . 'umbral', '' . "\0" . 'Cupon\\OfertaBundle\\Entity\\Oferta' . "\0" . 'revisada', '' . "\0" . 'Cupon\\OfertaBundle\\Entity\\Oferta' . "\0" . 'ciudad', '' . "\0" . 'Cupon\\OfertaBundle\\Entity\\Oferta' . "\0" . 'tienda');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Oferta $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre($nombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', array($nombre));

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', array());

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setSlug($slug)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSlug', array($slug));

        return parent::setSlug($slug);
    }

    /**
     * {@inheritDoc}
     */
    public function getSlug()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSlug', array());

        return parent::getSlug();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescripcion($descripcion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescripcion', array($descripcion));

        return parent::setDescripcion($descripcion);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescripcion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescripcion', array());

        return parent::getDescripcion();
    }

    /**
     * {@inheritDoc}
     */
    public function setCondiciones($condiciones)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCondiciones', array($condiciones));

        return parent::setCondiciones($condiciones);
    }

    /**
     * {@inheritDoc}
     */
    public function getCondiciones()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCondiciones', array());

        return parent::getCondiciones();
    }

    /**
     * {@inheritDoc}
     */
    public function setRutaFoto($rutaFoto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRutaFoto', array($rutaFoto));

        return parent::setRutaFoto($rutaFoto);
    }

    /**
     * {@inheritDoc}
     */
    public function getRutaFoto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRutaFoto', array());

        return parent::getRutaFoto();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrecio($precio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrecio', array($precio));

        return parent::setPrecio($precio);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrecio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrecio', array());

        return parent::getPrecio();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescuento($descuento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescuento', array($descuento));

        return parent::setDescuento($descuento);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescuento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescuento', array());

        return parent::getDescuento();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaPublicacion($fechaPublicacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaPublicacion', array($fechaPublicacion));

        return parent::setFechaPublicacion($fechaPublicacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaPublicacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaPublicacion', array());

        return parent::getFechaPublicacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaExpiracion($fechaExpiracion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaExpiracion', array($fechaExpiracion));

        return parent::setFechaExpiracion($fechaExpiracion);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaExpiracion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaExpiracion', array());

        return parent::getFechaExpiracion();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompras($compras)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompras', array($compras));

        return parent::setCompras($compras);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompras()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompras', array());

        return parent::getCompras();
    }

    /**
     * {@inheritDoc}
     */
    public function setUmbral($umbral)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUmbral', array($umbral));

        return parent::setUmbral($umbral);
    }

    /**
     * {@inheritDoc}
     */
    public function getUmbral()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUmbral', array());

        return parent::getUmbral();
    }

    /**
     * {@inheritDoc}
     */
    public function setRevisada($revisada)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRevisada', array($revisada));

        return parent::setRevisada($revisada);
    }

    /**
     * {@inheritDoc}
     */
    public function getRevisada()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRevisada', array());

        return parent::getRevisada();
    }

    /**
     * {@inheritDoc}
     */
    public function setCiudad(\Cupon\CiudadBundle\Entity\Ciudad $ciudad)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCiudad', array($ciudad));

        return parent::setCiudad($ciudad);
    }

    /**
     * {@inheritDoc}
     */
    public function getCiudad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCiudad', array());

        return parent::getCiudad();
    }

    /**
     * {@inheritDoc}
     */
    public function setTienda(\Cupon\TiendaBundle\Entity\Tienda $tienda)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTienda', array($tienda));

        return parent::setTienda($tienda);
    }

    /**
     * {@inheritDoc}
     */
    public function getTienda()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTienda', array());

        return parent::getTienda();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

}
